# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdfupload',
            name='owner',
            field=models.CharField(default='Name', max_length=64),
        ),
    ]
