# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skosapp', '0002_auto_20160722_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdfupload',
            name='corpus_id',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='rdfupload',
            name='project_id',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
