# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skosapp', '0003_auto_20160906_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdfupload',
            name='corpus_id',
        ),
        migrations.RemoveField(
            model_name='rdfupload',
            name='project_id',
        ),
        migrations.AddField(
            model_name='rdfupload',
            name='corpus_ID',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='rdfupload',
            name='project_ID',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
