# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skosapp', '0004_auto_20160909_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesaurusUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('thesaurus_file', models.FileField(upload_to='thesaurus_data/', verbose_name='File')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('project_ID', models.CharField(default=None, max_length=128)),
            ],
        ),
    ]
